### ISSUE TITLE
分片下载分配range是不是有些问题

### ISSUE THREAD

**Issue by kirovj** [ClassmateLin/douyin-downloader#2]
```
while end <= self.total_size() {
    end += chunk_size;
    range_list.push((start, end));
    start = end + 1;
}
```
当 end = total_size 时, range_list 还会 push 一条超过 total_size 的 start, end
是否应该改成下面这样？
```
while end < self.total_size() {
    end += chunk_size;
    if end > self.total_size() {
        end = self.total_size();
    }
    range_list.push((start, end));
    start = end + 1;
}
```

**Comment by ClassmateLin** [comment]
> ```
> while end <= self.total_size() {
>     end += chunk_size;
>     range_list.push((start, end));
>     start = end + 1;
> }
> ```
> 
> 当 end = total_size 时, range_list 还会 push 一条超过 total_size 的 start, end 是否应该改成下面这样？
> 
> ```
> while end < self.total_size() {
>     end += chunk_size;
>     if end > self.total_size() {
>         end = self.total_size();
>     }
>     range_list.push((start, end));
>     start = end + 1;
> }
> ```

确实会多推送一条
