### ISSUE TITLE
下载文件夹里找不到下载的视频

### ISSUE THREAD

**Issue by EX-Miracle** [ClassmateLin/douyin-downloader#3]
虽然提示下载已完成，但是打开下载文件夹会发现并没有要下载的视频

**Comment by ClassmateLin** [comment]
> 虽然提示下载已完成，但是打开下载文件夹会发现并没有要下载的视频

能否提供操作步骤和截图呢?

**Comment by EX-Miracle** [comment]
![22-11-21 16-55-46](https://user-images.githubusercontent.com/70376567/203008171-4b44ea91-3d9a-4f37-bd92-e581cc781031.gif)

**Comment by ClassmateLin** [comment]
> ![22-11-21 16-55-46](https://user-images.githubusercontent.com/70376567/203008171-4b44ea91-3d9a-4f37-bd92-e581cc781031.gif) [ ![22-11-21 16-55-46](https://user-images.githubusercontent.com/70376567/203008171-4b44ea91-3d9a-4f37-bd92-e581cc781031.gif) ](https://user-images.githubusercontent.com/70376567/203008171-4b44ea91-3d9a-4f37-bd92-e581cc781031.gif) [ ](https://user-images.githubusercontent.com/70376567/203008171-4b44ea91-3d9a-4f37-bd92-e581cc781031.gif)

建议尝试以下操作，以便我定位问题。(顺带可以提供你使用的用户主页链接)
1. 尝试在你的D盘目录建一个英文的文件夹，看是否可以下载保存。
2. 如果1不行, 再尝试下载标题不带\n的视频试试。

**Comment by EX-Miracle** [comment]
试了下应该是 \n 的问题，如果不带 \n 的话，不管路径中有没有中文都是可以下载的

长按复制此条消息，打开抖音搜索，查看TA的更多作品。 https://v.douyin.com/r9Bhmrr/

**Comment by ClassmateLin** [comment]
> 试了下应该是 \n 的问题，如果不带 \n 的话，不管路径中有没有中文都是可以下载的
> 
> 长按复制此条消息，打开抖音搜索，查看TA的更多作品。 https://v.douyin.com/r9Bhmrr/

v0.1.5已解决该问题
